
services:
  - mongodb
language: ruby
rvm:
 - 2.3.1
cache: bundler 

before_script:
  - cd $TRAVIS_BUILD_DIR/test/dummy && bundle install --path vendor/bundle

script: 
  - cd $TRAVIS_BUILD_DIR/test/dummy && bundle exec rspec spec

