
services:
  - mongodb
language: ruby
rvm:
 - 2.3.1

cache: bundler 

install:
  - gem install bundler
  - bundle install --gemfile=test/dummy/Gemfile --path vendor/bundle

script: 
  - bundle exec rspec test/dummy/spec -I test/dummy/spec


